### PR TITLE
Add the speaker list

### PR DESCRIPTION
**Pull request by matthewmayer**
## What happened

- Add speakers page including non-keynote speakers. 
- Change twitter link to allow one twitter or mastodon `social_url` plus a `website`
 
## Insight

Information was provided by speakers via a Google form. 

## Proof Of Work

|Small Screen|Large Screen|
|-|-|
|image|image|

### CODE REVIEW

**Comment by olivierobert** [comment]
@citizen428 With Matt away, can you check the content for the speakers? Is it now complete so that it can be published?

**Comment by citizen428** [comment]
@olivierobert Sorry, I was/am busy and didn't see your message until now. I'll let you know by tomorrow the latest, but I think there might still be speakers missing.

**Comment by matthewmayer** [comment]
There are some outstanding will paste the link on slack

**Comment by matthewmayer** [comment]
i think this can be merged now, we can add Steven Baker when we get the info and Lachlan when confirmed.

**Review by citizen428 — APPROVED** [review]

**Review by olivierobert — APPROVED** [review]

**Pull request merged**
